all:
	#g++ -I /usr/include/eigen2 Main.cpp Cylinder2d.cpp Manifold.cpp -lglut -o cylinder -lGL -lGLU
	g++ -I /usr/include/eigen2 Main.cpp PortalSpace2d2.cpp Hyperbolic2d.cpp Manifold.cpp -lglut -o wormhole -lGL -lGLU
	#g++ -I /usr/include/eigen2 Main.cpp BlackHole2d.cpp Hyperbolic2d.cpp Manifold.cpp -lglut -o blackhole -lGL -lGLU
	#g++ -I /usr/include/eigen2 Main2.cpp PortalSpace2d2.cpp Hyperbolic2d.cpp -lglut -o wormhole2d -lGL -lGLU
	#g++ -I /usr/include/eigen2 Main2.cpp BlackHole2d.cpp Hyperbolic2d.cpp -lglut -o blackhole2d -lGL -lGLU
	#g++ -I /usr/include/eigen2 Main2.cpp Hyperbolic2d.cpp -lglut -o hyperbolic2d -lGL -lGLU
